### ISSUE TITLE
Concurrency when using TestServer

### ISSUE THREAD

**Issue by ericywl** [JosephLenton/axum-test#78]
## Problem

I was trying to do some concurrency testing on my app and ran into this issue. The following is a simplified snippet:

```rs
#[tokio::test]
async fn test_something() {
    let app = axum::Router::new().route(
        &"/todo",
        axum::routing::get(|| async {
            tokio::time::sleep(std::time::Duration::from_secs(1)).await;
            "hello!"
        }),
    );
    let server = axum_test::TestServer::new(app).unwrap();

    let future1 = async { server.get("/todo").await };
    let future2 = async { server.get("/todo").await };
    let (r1, r2) = tokio::join!(future1, future2);

    assert_eq!(r1.text(), r2.text());
}
```

It seems this code does not halt, not sure if its due to some internal workings of the `TestServer` or if I did something wrong.

## Environment

Cargo.toml:
```toml
[dependencies]
axum = { version = "0.7.5", features = ["macros"] }
axum-test = "14.10.0"
tokio = { version = "1.38.0", features = ["full"] }
```
